---
title: "R Notebook"
output: html_notebook
---

```{r}
library(dplyr)
library(tidyr)
library(knitr)
library(kableExtra)
library(ggplot2)
data<- read.csv("graphembedding.csv")
colnames(data)<- c("Algorithm","Metric","Value")
data
```

```{r}
p <- ggplot(data,aes(x=Metric,y=Value,color=Algorithm,fill=Algorithm,shape=Algorithm))+
  geom_point(size = 2)+
  scale_shape_manual(values = c(21, 22, 23, 24, 25,15),
                     name = NULL)+
  scale_color_manual(values = c("#0072b2", "#D55E00", "#009e73", "#E69F00","#999999","#714399"),name = NULL) +
  scale_fill_manual(values = c("#0072b2", "#D55E00", "#009e73", "#E69F00","#999999","#714399"),name = NULL) +
  
  theme_classic() +

  theme(legend.title.align = 0.5,
        legend.position = c(0.005, 1.05),
        legend.just = c(0, 1),
        plot.margin = margin(14, 7, 3, 1.5))

p
```

```{r fig.height = 5.5, fig.width = 16,warning = FALSE,message=FALSE}
p<-ggplot(data=data, aes(x=Metric, y=Value,color=Algorithm)) +
  geom_point(size=2)+
    scale_color_manual(values = c("#0072b2", "#D55E00", "#009e73", "#E69F00","#999999","#714399"),name = NULL) +
  scale_fill_manual(values = c("#0072b2", "#D55E00", "#009e73", "#E69F00","#999999","#714399"),name = NULL) +
  theme_classic() +

  theme(legend.title.align = 0.5,
        legend.position = c(0.005, 1.05),
        legend.just = c(0, 1),
        plot.margin = margin(14, 7, 3, 1.5))
ggsave("algo-compare.png")
p
```
```{r}
data<- read.csv("entitycounts.csv")
colnames(data)<- c("Entity","Count")
data
```

```{r fig.height = 3, fig.width = 10,warning = FALSE,message=FALSE}
library(ggplot2)

theme_set(theme_classic())


p <-ggplot(data, (aes(x= reorder(Entity, Count) , y=Count))) + 
  geom_col(fill="#66c2a5", width=0.5,position = position_dodge(width = 0.1))+
   scale_y_continuous(sec.axis = dup_axis(),
                      breaks = c( 10000,20000,30000,40000,50000,60000 ),
                     labels = c("10000","20000","30000","40000","50000","60000" ),
                     name = "weekend gross (x €1,000)")+
  geom_text(aes(label=Count), size =3.5, vjust=0,hjust=-0.2)+

  coord_flip(clip = "off") +
    theme(
      axis.title = element_blank(),
      axis.line.y = element_blank(),
      axis.ticks.y = element_blank(),
      axis.line.x = element_blank(),
      axis.ticks.x = element_blank(),
      axis.title.y = element_blank(),
      axis.title.x.bottom =  element_blank(),
      axis.text.x.bottom =  element_blank(),
     plot.title = element_text(size = 11),
      plot.margin = margin(3, 6, 3, 3),
      panel.background = element_blank(),
      panel.grid.major.x = element_line(size = 0.4, linetype = 'solid',colour = "white"),
      panel.ontop = TRUE)

ggsave("entity-count.png")
p

```

```{r}
data2<- read.csv("relationshipcounts.csv")
colnames(data2)<- c("Relationship","Count")
data2
```
```{r fig.height = 5, fig.width = 10,warning = FALSE,message=FALSE}
library(ggplot2)

theme_set(theme_classic())


p <-ggplot(data2, (aes(x= reorder(Relationship, Count) , y=Count))) + 
  geom_col(fill="#fc8d62", width=0.5,position = position_dodge(width = 0.9))+
   scale_y_continuous(sec.axis = dup_axis(),
                      breaks = c( 5000,10000,15000,20000,25000),
                     labels = c("5000","10000","15000","20000","25000" ),
                     name = "weekend gross (x €1,000)")+
  geom_text(aes(label=Count), size =3.5, vjust=0,hjust=-0.2)+

  coord_flip(clip = "off") +
    theme(
      axis.title = element_blank(),
      axis.line.y = element_blank(),
      axis.ticks.y = element_blank(),
      axis.line.x = element_blank(),
      axis.ticks.x = element_blank(),
      axis.title.y = element_blank(),
      axis.title.x.bottom =  element_blank(),
      axis.text.x.bottom =  element_blank(),
     plot.title = element_text(size = 11),
      plot.margin = margin(3, 6, 3, 3),
      panel.background = element_blank(),
      panel.grid.major.x = element_line(size = 0.4, linetype = 'solid',colour = "white"),
      panel.ontop = TRUE)

ggsave("relationship-compare.png")
p
```
```{r}
data<- read.csv("drugLinks.txt")
colnames(data)<- c("Links")
data
```

```{r}
library(ggplot2)

ggplot(data, aes(x=Links)) + 
  
  geom_density(fill = "#66c2a5", 
               col = "black", 
               bw = 1, alpha= 0.5) +
  ggtitle("Distribution of relationship count for Drugs")+
  
  scale_x_continuous(expand=c(0,0), breaks = seq(0,50, by=5)) +
  theme_minimal() +
  ylab("Density")+
  theme(text = element_text(size=15),
        panel.grid.minor.y = element_blank(),
        panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank())

```
```{r}
data<- read.csv("diseaseLinks.txt")
colnames(data)<- c("Links")
data
```

```{r}
ggplot(data, aes(x=Links)) + 
  
  geom_density(fill = "#7570B3", 
               col = "black", 
               bw = 1, alpha= 0.5) +
  ggtitle("Distribution of relationship count for Diseases")+
  
  scale_x_continuous(expand=c(0,0), breaks = seq(0,100, by=10)) +
  theme_minimal() +
  ylab("Density")+
  theme(text = element_text(size=15),
        panel.grid.minor.y = element_blank(),
        panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank())
```
```{r}
data<- read.csv("pathwayLinks.txt")
colnames(data)<- c("Links")
data
```
```{r}
ggplot(data, aes(x=Links)) + 
  
  geom_density(fill = "#A6761D", 
               col = "black", 
               bw = 1, alpha= 0.5) +
  ggtitle("Distribution of relationship count for Pathways")+
  
  scale_x_continuous(expand=c(0,0), breaks = seq(0,2200, by=200)) +
  theme_minimal() +
  ylab("Density")+
  theme(text = element_text(size=15),
        panel.grid.minor.y = element_blank(),
        panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank())
```

```{r}
data<- read.csv("geneLinks.txt")
colnames(data)<- c("Links")
data
```

```{r}
ggplot(data, aes(x=Links)) + 
  
  geom_density(fill = "#E6AB02", 
               col = "black", 
               bw = 1, alpha= 0.5) +
  ggtitle("Distribution of relationship count for Genes")+
  
  scale_x_continuous(expand=c(0,0), breaks = seq(0,210, by=10)) +
  theme_minimal() +
  ylab("Density")+
  theme(text = element_text(size=15),
        panel.grid.minor.y = element_blank(),
        panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank())
```

```{r}
data<- read.csv("networkLinks.txt")
colnames(data)<- c("Links")
data
```
```{r}
ggplot(data, aes(x=Links)) + 
  
  geom_density(fill = "#D95F02", 
               col = "black", 
               bw = 1, alpha= 0.5) +
  ggtitle("Distribution of relationship count for Networks")+
  
  scale_x_continuous(expand=c(0,0), breaks = seq(0,50, by=5)) +
  theme_minimal() +
  ylab("Density")+
  theme(text = element_text(size=15),
        panel.grid.minor.y = element_blank(),
        panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank())
```

